CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
SCENE_TOKEN_INDEX = -201
TRACK_TOKEN_INDEX = -202
MAP_TOKEN_INDEX = -203
OBJECT_TOKEN_INDEX = -204

DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

DEFAULT_IMAGE_TOKEN = "<IMAGE>"
DEFAULT_SCENE_TOKEN = "<SCENE>"
DEFAULT_TRACK_TOKEN = "<TRACK>"
DEFAULT_MAP_TOKEN = "<MAP>"
DEFAULT_OBJECT_TOKEN = "<OBJECT>"

DEFAULT_TRAJ_TOKEN = "<trajectory>"

DEFAULT_TRACK_START_TOKEN = "<track_start>"
DEFAULT_TRACK_END_TOKEN = "<track_end>"

DEFAULT_TRAJ_START_TOKEN="<traj_start>"
DEFAULT_TRAJ_END_TOKEN="<traj_end>"

# DEFAULT_OBJ_START_TOKEN="<obj_start>"
# DEFAULT_OBJ_END_TOKEN="<obj_end>"

DEFAULT_SCENE_START_TOKEN="<scene_start>"
DEFAULT_SCENE_END_TOKEN="<scene_end>"

DEFAULT_MAP_START_TOKEN="<map_start>"
DEFAULT_MAP_END_TOKEN="<map_end>"

DEFAULT_EGO_START_TOKEN="<ego_start>"
DEFAULT_EGO_END_TOKEN="<ego_end>"

DEFAULT_COMMAND_START_TOKEN="<command_start>"
DEFAULT_COMMAND_END_TOKEN="<command_end>"

DEFAULT_QUESTION_START="<question_start>"
DEFAULT_QUESTION_END="<question_end>"

DEFAULT_ANSWER_START="<answer_start>"
DEFAULT_ANSWER_END="<answer_end>"